services:
  - type: web
    name: agentic-ai-pdf-assistant
    runtime: python
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install streamlit==1.30.0
    startCommand: python -m streamlit run app_test.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --browser.gatherUsageStats=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    autoDeploy: true
