services:
  - type: web
    name: agentic-ai-pdf-assistant
    runtime: python
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install streamlit==1.30.0 groq==0.5.0 pypdf==4.0.0
    startCommand: python run_streamlit.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    autoDeploy: true
