services:
  - type: web
    name: agentic-ai-pdf-assistant
    runtime: python
    buildCommand: pip install streamlit groq pypdf
    startCommand: streamlit run app_lite.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    autoDeploy: true
