services:
  - type: web
    name: agentic-ai-pdf-assistant
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    autoDeploy: true
